### ISSUE TITLE
Black screen booting linux (kubuntu 19.10) with clover

### ISSUE THREAD

**Issue by pagimamaun** [ReddestDream/OcQuirks#20]
Hello
My problem is when using OcQuirks with clover, i can't boot anymore ubuntu via clover 
Starting unbuntu failed after grub and at initialising ramdisk
Thanks for your help

**Comment by ReddestDream** [comment]
You may need to try different configuration settings in the OcQuirks.plist.

**Comment by ReddestDream** [comment]
This issue was fixed by OpenCore Upstream. Please let me know if you'd like a recompiled version that includes this fix. Thanks! https://github.com/acidanthera/OpenCorePkg/commit/3f2069d352646150750365afb3cf4c2330c606ab

**Comment by pagimamaun** [comment]
Hello
I think release 20.1 is the recompiled version
I tried it with no luck, i'm still unable to boot linux
Thanks for your help

**Comment by ReddestDream** [comment]
Good to know. Work is still being done on more fixes. I'll bring them to OcQuirks over the weekend. Thanks!

**Comment by pagimamaun** [comment]
Thanks

**Comment by ReddestDream** [comment]
Please try this new version. Thx!

**Comment by pagimamaun** [comment]
Hello, it's working. Great work Thank you
